<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\BuildingBlocks\YO4X.Api\YO4X.Api.csproj" />
    <ProjectReference Include="..\..\src\Apps\YO4X.ControlPlane.Api\YO4X.ControlPlane.Api.csproj" />
    <ProjectReference Include="..\..\src\Apps\YO4X.SecretIngestion.Api\YO4X.SecretIngestion.Api.csproj" />
    <ProjectReference Include="..\..\src\Infrastructure\YO4X.RuntimeControl.Postgres\YO4X.RuntimeControl.Postgres.csproj" />
  </ItemGroup>

</Project>
