//+------------------------------------------------------------------+
//|                                                   OliverKell.mq5 |
//|                                                Generated by AI   |
//+------------------------------------------------------------------+
#property copyright "AI Assistant"
#property link      ""
#property version   "1.00"
#include <Trade\Trade.mqh>
#include <Trade\PositionInfo.mqh>
#include <Trade\SymbolInfo.mqh>
#include <Trade\AccountInfo.mqh>
//--- Input parameters
input string   Group1="--- Risk Management ---";
input double   InpRiskPercent       = 1.0;      // Risk per trade (%)
input int      InpTrailingStopPips  = 50;       // Trailing Stop (pips)
input string   Group2="--- Strategy Parameters ---";
input int      InpEmaFastPeriod     = 10;       // Fast EMA Period
input int      InpEmaSlowPeriod     = 20;       // Slow EMA Period
input int      InpBaseLookback      = 10;       // Base Lookback (bars)
input double   InpMaxBaseWidthATR   = 2.0;      // Max Base Width (in ATR)
input int      InpAtrPeriod         = 14;       // ATR Period
input int      InpVolMaPeriod       = 20;       // Volume MA Period
input string   Group3="--- Expert Settings ---";
input ulong    InpMagicNumber       = 983000;   // Magic Number (983% reference)
input string   InpTradeComment      = "OliverKell";
//--- Global objects and variables
CTrade         trade;
CPositionInfo  posInfo;
CSymbolInfo    symInfo;
CAccountInfo   accInfo;
int            handleEmaFast;
int            handleEmaSlow;
int            handleAtr;
double         emaFastArr[];
double         emaSlowArr[];
double         atrArr[];
long           volArr[];
//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
  {
   trade.SetExpertMagicNumber(InpMagicNumber);
   
   if(!symInfo.Name(_Symbol))
     {
      Print("Failed to initialize CSymbolInfo");
      return(INIT_FAILED);
     }
   symInfo.RefreshRates();
   handleEmaFast = iMA(_Symbol, PERIOD_CURRENT, InpEmaFastPeriod, 0, MODE_EMA, PRICE_CLOSE);
   handleEmaSlow = iMA(_Symbol, PERIOD_CURRENT, InpEmaSlowPeriod, 0, MODE_EMA, PRICE_CLOSE);
   handleAtr = iATR(_Symbol, PERIOD_CURRENT, InpAtrPeriod);
   if(handleEmaFast == INVALID_HANDLE || handleEmaSlow == INVALID_HANDLE || handleAtr == INVALID_HANDLE)
     {
      Print("Failed to create indicator handles");
      return(INIT_FAILED);
     }
   ArraySetAsSeries(emaFastArr, true);
   ArraySetAsSeries(emaSlowArr, true);
   ArraySetAsSeries(atrArr, true);
   ArraySetAsSeries(volArr, true);
   return(INIT_SUCCEEDED);
  }
//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
  {
   IndicatorRelease(handleEmaFast);
   IndicatorRelease(handleEmaSlow);
   IndicatorRelease(handleAtr);
   Comment("");
  }
//+------------------------------------------------------------------+
//| Check for new bar                                                |
//+------------------------------------------------------------------+
bool IsNewBar()
  {
   static datetime lastTime = 0;
   datetime currentTime = iTime(_Symbol, PERIOD_CURRENT, 0);
   if(currentTime != lastTime)
     {
      lastTime = currentTime;
      return true;
     }
   return false;
  }
//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
  {
   symInfo.RefreshRates();
   // Update arrays
   if(CopyBuffer(handleEmaFast, 0, 0, 3, emaFastArr) <= 0) return;
   if(CopyBuffer(handleEmaSlow, 0, 0, 3, emaSlowArr) <= 0) return;
   if(CopyBuffer(handleAtr, 0, 0, 3, atrArr) <= 0) return;
   if(CopyTickVolume(_Symbol, PERIOD_CURRENT, 0, InpVolMaPeriod + 2, volArr) <= 0) return;
   // Display info on chart
   UpdateDashboard();
   // Trailing Stop logic (runs on every tick)
   ManageTrailingStop();
   // Entry and Exit logic runs on new bar
   if(IsNewBar())
     {
      CheckExit();
      CheckEntry();
     }
  }
//+------------------------------------------------------------------+
//| Check Entry Logic                                                |
//+------------------------------------------------------------------+
void CheckEntry()
  {
   bool hasPos = false;
   for(int i=PositionsTotal()-1; i>=0; i--)
     {
      if(posInfo.SelectByIndex(i))
        {
         if(posInfo.Symbol() == _Symbol && posInfo.Magic() == InpMagicNumber)
           {
            hasPos = true;
            break;
           }
        }
     }
     
   if(hasPos) return; // Only one position at a time
   // Calculate average volume
   long sumVol = 0;
   for(int i = 2; i <= InpVolMaPeriod + 1; i++) // Average of previous N bars
     {
      sumVol += volArr[i];
     }
   long avgVol = sumVol / InpVolMaPeriod;
   
   long lastVol = volArr[1]; // Volume of the just closed bar
   // Find Base High and Base Low
   double baseHigh = 0;
   double baseLow = 9999999;
   
   for(int i = 2; i <= InpBaseLookback + 1; i++) // Past N bars excluding the breakout bar
     {
      double h = iHigh(_Symbol, PERIOD_CURRENT, i);
      double l = iLow(_Symbol, PERIOD_CURRENT, i);
      if(h > baseHigh) baseHigh = h;
      if(l < baseLow) baseLow = l;
     }
   double close1 = iClose(_Symbol, PERIOD_CURRENT, 1);
   double close2 = iClose(_Symbol, PERIOD_CURRENT, 2);
   
   double currentAtr = atrArr[1];
   bool isBaseTight = (baseHigh - baseLow) <= (InpMaxBaseWidthATR * currentAtr);
   
   bool isAboveEma = close1 > emaFastArr[1] && close1 > emaSlowArr[1];
   // Breakout: we broke above the base high recently
   bool isBreakout = close1 > baseHigh && close2 <= baseHigh;
   bool isStrongVol = lastVol > avgVol;
   if(isBaseTight && isAboveEma && isBreakout && isStrongVol)
     {
      // Calculate Stop Loss
      double sl = baseLow; 
      // Ensure slight buffer
      double tickSize = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
      sl -= 2 * tickSize;
      double ticks = (symInfo.Ask() - sl) / tickSize;
      if(ticks <= 0) return;
      
      double tickValue = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
      double riskAmount = accInfo.Balance() * (InpRiskPercent / 100.0);
      
      double stepVol = symInfo.LotsStep();
      
      double lotSize = 0;
      if (tickValue > 0 && ticks > 0) {
          lotSize = riskAmount / (ticks * tickValue);
      }
      
      double minLot = symInfo.LotsMin();
      double maxLot = symInfo.LotsMax();
      
      // Normalize lot size
      lotSize = MathFloor(lotSize / stepVol) * stepVol;
      if(lotSize < minLot) lotSize = minLot;
      if(lotSize > maxLot) lotSize = maxLot;
      trade.Buy(lotSize, _Symbol, symInfo.Ask(), sl, 0, InpTradeComment);
     }
  }
//+------------------------------------------------------------------+
//| Check Exit Logic                                                 |
//+------------------------------------------------------------------+
void CheckExit()
  {
   for(int i=PositionsTotal()-1; i>=0; i--)
     {
      if(posInfo.SelectByIndex(i))
        {
         if(posInfo.Symbol() == _Symbol && posInfo.Magic() == InpMagicNumber)
           {
            // Exit rule: "sell on 'EMA Crossback' where price closes below 10 & 20 EMAs"
            double close1 = iClose(_Symbol, PERIOD_CURRENT, 1);
            if(close1 < emaFastArr[1] && close1 < emaSlowArr[1])
              {
               if(posInfo.PositionType() == POSITION_TYPE_BUY)
                 {
                  trade.PositionClose(posInfo.Ticket());
                 }
              }
           }
        }
     }
  }
//+------------------------------------------------------------------+
//| Manage Trailing Stop                                             |
//+------------------------------------------------------------------+
void ManageTrailingStop()
  {
   if(InpTrailingStopPips <= 0) return;
   
   double pipsToPrice = InpTrailingStopPips * ((_Digits == 3 || _Digits == 5) ? 10 : 1) * symInfo.Point();
   for(int i=PositionsTotal()-1; i>=0; i--)
     {
      if(posInfo.SelectByIndex(i))
        {
         if(posInfo.Symbol() == _Symbol && posInfo.Magic() == InpMagicNumber)
           {
            if(posInfo.PositionType() == POSITION_TYPE_BUY)
              {
               if(symInfo.Bid() - posInfo.PriceOpen() > pipsToPrice)
                 {
                  double newSl = symInfo.Bid() - pipsToPrice;
                  if(posInfo.StopLoss() < newSl || posInfo.StopLoss() == 0)
                    {
                     trade.PositionModify(posInfo.Ticket(), newSl, posInfo.TakeProfit());
                    }
                 }
              }
           }
        }
     }
  }
//+------------------------------------------------------------------+
//| Update Dashboard Info                                            |
//+------------------------------------------------------------------+
void UpdateDashboard()
  {
   // Calculate average volume for display
   long sumVol = 0;
   for(int i = 1; i <= InpVolMaPeriod; i++)
     {
      sumVol += volArr[i];
     }
   long avgVol = sumVol / InpVolMaPeriod;
   string dashboard = "=== Oliver Kell Strategy ===\n\n";
   dashboard += StringFormat("Fast EMA (%d): %.5f\n", InpEmaFastPeriod, emaFastArr[0]);
   dashboard += StringFormat("Slow EMA (%d): %.5f\n", InpEmaSlowPeriod, emaSlowArr[0]);
   dashboard += StringFormat("Last Vol: %I64d (Avg %d: %I64d)\n\n", volArr[1], InpVolMaPeriod, avgVol);
   
   dashboard += "=== Risk Management ===\n";
   dashboard += StringFormat("Risk Per Trade: %.2f%%\n", InpRiskPercent);
   dashboard += "Position Sizing: Dynamic based on Stop Loss\n\n";
   
   dashboard += "=== Current Status ===\n";
   
   bool hasPos = false;
   for(int i=PositionsTotal()-1; i>=0; i--)
     {
      if(posInfo.SelectByIndex(i))
        {
         if(posInfo.Symbol() == _Symbol && posInfo.Magic() == InpMagicNumber)
           {
            dashboard += StringFormat("Open Position: %s %.2f Lots\n", EnumToString(posInfo.PositionType()), posInfo.Volume());
            dashboard += StringFormat("Open Price: %.5f\n", posInfo.PriceOpen());
            dashboard += StringFormat("Stop Loss: %.5f\n", posInfo.StopLoss());
            dashboard += StringFormat("Profit: %.2f\n", posInfo.Profit());
            hasPos = true;
            break;
           }
        }
     }
     
   if(!hasPos)
     {
      dashboard += "Waiting for Base 'n Break setup...\n\n";
      // Find current base for display
      double baseHigh = 0; double baseLow = 9999999;
      for(int i = 1; i <= InpBaseLookback; i++)
        {
         double h = iHigh(_Symbol, PERIOD_CURRENT, i);
         double l = iLow(_Symbol, PERIOD_CURRENT, i);
         if(h > baseHigh) baseHigh = h;
         if(l < baseLow) baseLow = l;
        }
      dashboard += StringFormat("Current Base High: %.5f\n", baseHigh);
      dashboard += StringFormat("Current Base Low: %.5f\n", baseLow);
      
      double currentAtr = atrArr[0];
      bool isBaseTight = (baseHigh - baseLow) <= (InpMaxBaseWidthATR * currentAtr);
      string tightStr = isBaseTight ? "YES" : "NO";
      dashboard += StringFormat("Base Tightness (<= %.2f ATR): %s\n", InpMaxBaseWidthATR, tightStr);
     }
     
   Comment(dashboard);
  }
//+------------------------------------------------------------------+