//+------------------------------------------------------------------+
//|                                                OlliverKillEA.mq5  |
//|                                     Generated by AI Assistant     |
//+------------------------------------------------------------------+
#property copyright "Simple Forex Tools"
#property link      "https://t.me/simpleforextools"
#property version   "1.10"
#property strict

#include <Trade/Trade.mqh>

//--- Input parameters
input string   Group1="--- Risk Management ---";
input double   InpRiskPercent              = 1.0;      // Risk per initial trade (%)
input double   InpScaleInRiskPercent       = 0.5;      // Risk per scale-in trade (%)
input int      InpMaxPositions             = 2;        // Max positions per symbol
input int      InpTrailingStopPips         = 50;       // Trailing Stop (pips)
input int      InpMaxSpreadPips            = 0;        // Max spread (pips, 0=off)

input string   Group2="--- Strategy Parameters ---";
input int      InpEmaFastPeriod            = 10;       // Fast EMA Period
input int      InpEmaSlowPeriod            = 20;       // Slow EMA Period
input int      InpBaseLookback             = 10;       // Base Lookback (bars)
input double   InpMaxBaseWidthATR          = 2.0;      // Max Base Width (in ATR)
input int      InpAtrPeriod                = 14;       // ATR Period
input int      InpVolMaPeriod              = 20;       // Volume MA Period

input string   Group3="--- Oliver Kell Pattern Rules ---";
input bool     InpTradeBaseBreak           = true;     // Trade Base 'n Break
input bool     InpTradeWedgePop            = true;     // Trade Wedge Pop continuation
input bool     InpTradeEmaCrossback        = true;     // Trade EMA Crossback continuation
input bool     InpExitExhaustionExtension  = true;     // Exit on Exhaustion Extension
input bool     InpExitWedgeDrop            = true;     // Exit on Wedge Drop
input double   InpExtensionAtrMultiple     = 2.5;      // Exhaustion distance from 20 EMA (ATR)
input int      InpWedgeLookback            = 6;        // Wedge lookback bars
input double   InpMinScaleInProfitPips     = 25;       // Min profit before scale-in

input string   Group4="--- Expert Settings ---";
input int      InpMagicNumber              = 983000;   // Magic Number
input string   InpTradeComment             = "OliverKell";

CTrade g_trade;
datetime g_lastEntryBarTime = 0;
int g_emaFastHandle = INVALID_HANDLE;
int g_emaSlowHandle = INVALID_HANDLE;
int g_atrHandle = INVALID_HANDLE;

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
  {
   g_trade.SetExpertMagicNumber(InpMagicNumber);
   g_trade.SetDeviationInPoints(3);

   g_emaFastHandle = iMA(_Symbol, _Period, InpEmaFastPeriod, 0, MODE_EMA, PRICE_CLOSE);
   g_emaSlowHandle = iMA(_Symbol, _Period, InpEmaSlowPeriod, 0, MODE_EMA, PRICE_CLOSE);
   g_atrHandle = iATR(_Symbol, _Period, InpAtrPeriod);

   if(g_emaFastHandle == INVALID_HANDLE || g_emaSlowHandle == INVALID_HANDLE || g_atrHandle == INVALID_HANDLE)
     {
      Print("Failed to create indicator handles. Error #", GetLastError());
      return INIT_FAILED;
     }

   return INIT_SUCCEEDED;
  }

//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
  {
   Comment("");
   if(g_emaFastHandle != INVALID_HANDLE) IndicatorRelease(g_emaFastHandle);
   if(g_emaSlowHandle != INVALID_HANDLE) IndicatorRelease(g_emaSlowHandle);
   if(g_atrHandle != INVALID_HANDLE) IndicatorRelease(g_atrHandle);
  }

//+------------------------------------------------------------------+
//| Helpers                                                          |
//+------------------------------------------------------------------+
bool IsNewBar()
  {
   static datetime lastTime = 0;
   datetime currentTime = iTime(_Symbol, _Period, 0);
   if(currentTime != lastTime)
     {
      lastTime = currentTime;
      return true;
     }
   return false;
  }

double GetPipMultiplier()
  {
   int digits = (int)SymbolInfoInteger(_Symbol, SYMBOL_DIGITS);
   if(digits == 3 || digits == 5) return 10.0;
   return 1.0;
  }

double PipsToPrice(double pips)
  {
   return pips * GetPipMultiplier() * _Point;
  }

double NormalizePrice(double price)
  {
   int digits = (int)SymbolInfoInteger(_Symbol, SYMBOL_DIGITS);
   return NormalizeDouble(price, digits);
  }

int MaxInt(int a, int b)
  {
   if(a > b) return a;
   return b;
  }

bool GetBufferValue(const int handle, const int shift, double &value)
  {
   double buffer[1];
   if(CopyBuffer(handle, 0, shift, 1, buffer) != 1)
      return false;
   value = buffer[0];
   return true;
  }

double EmaFast(const int shift)
  {
   double value = 0;
   if(!GetBufferValue(g_emaFastHandle, shift, value)) return 0;
   return value;
  }

double EmaSlow(const int shift)
  {
   double value = 0;
   if(!GetBufferValue(g_emaSlowHandle, shift, value)) return 0;
   return value;
  }

double Atr(const int shift)
  {
   double value = 0;
   if(!GetBufferValue(g_atrHandle, shift, value)) return 0;
   return value;
  }

bool GetTickPrices(double &bid, double &ask)
  {
   MqlTick tick;
   if(!SymbolInfoTick(_Symbol, tick)) return false;
   bid = tick.bid;
   ask = tick.ask;
   return bid > 0 && ask > 0;
  }

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
  {
   UpdateDashboard();
   ManageTrailingStop();
   if(IsNewBar())
     {
      CheckExit();
      CheckEntry();
     }
  }

//+------------------------------------------------------------------+
//| Market helpers                                                   |
//+------------------------------------------------------------------+
bool HasEnoughBars()
  {
   int requiredBars = MaxInt(InpVolMaPeriod + 5, MaxInt(InpBaseLookback + 5, InpWedgeLookback + 5));
   requiredBars = MaxInt(requiredBars, InpAtrPeriod + 5);
   requiredBars = MaxInt(requiredBars, InpEmaSlowPeriod + 5);
   return Bars(_Symbol, _Period) > requiredBars;
  }

bool IsSpreadAllowed()
  {
   if(InpMaxSpreadPips <= 0) return true;

   double bid, ask;
   if(!GetTickPrices(bid, ask)) return false;
   return ask - bid <= PipsToPrice(InpMaxSpreadPips);
  }

int CountOwnPositions(const int positionType = -1)
  {
   int count = 0;
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0 || !PositionSelectByTicket(ticket)) continue;

      if(PositionGetString(POSITION_SYMBOL) != _Symbol) continue;
      if((int)PositionGetInteger(POSITION_MAGIC) != InpMagicNumber) continue;

      int type = (int)PositionGetInteger(POSITION_TYPE);
      if(positionType < 0 || type == positionType)
         count++;
     }
   return count;
  }

double GetBestOpenPrice()
  {
   double bestOpen = 0;
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0 || !PositionSelectByTicket(ticket)) continue;

      if(PositionGetString(POSITION_SYMBOL) != _Symbol) continue;
      if((int)PositionGetInteger(POSITION_MAGIC) != InpMagicNumber) continue;
      if((ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE) != POSITION_TYPE_BUY) continue;

      double openPrice = PositionGetDouble(POSITION_PRICE_OPEN);
      if(bestOpen == 0 || openPrice < bestOpen)
         bestOpen = openPrice;
     }
   return bestOpen;
  }

long AverageVolume(int startShift, int periods)
  {
   if(periods <= 0) return 0;
   long sumVol = 0;
   for(int i = startShift; i < startShift + periods; i++)
      sumVol += (long)iVolume(_Symbol, _Period, i);
   return sumVol / periods;
  }

void GetBaseRange(int startShift, int lookback, double &baseHigh, double &baseLow)
  {
   baseHigh = 0;
   baseLow = DBL_MAX;
   for(int i = startShift; i < startShift + lookback; i++)
     {
      double h = iHigh(_Symbol, _Period, i);
      double l = iLow(_Symbol, _Period, i);
      if(h > baseHigh) baseHigh = h;
      if(l < baseLow) baseLow = l;
     }
  }

bool IsTightBase(double baseHigh, double baseLow, int atrShift)
  {
   double currentAtr = Atr(atrShift);
   if(currentAtr <= 0) return false;
   return (baseHigh - baseLow) <= (InpMaxBaseWidthATR * currentAtr);
  }

bool IsStrongVolume(int signalShift)
  {
   long avgVol = AverageVolume(signalShift + 1, InpVolMaPeriod);
   long signalVol = (long)iVolume(_Symbol, _Period, signalShift);
   return avgVol > 0 && signalVol > avgVol;
  }

bool IsAboveTrend(int shift)
  {
   double close = iClose(_Symbol, _Period, shift);
   double emaFast = EmaFast(shift);
   double emaSlow = EmaSlow(shift);
   return close > emaFast && close > emaSlow && emaFast >= emaSlow;
  }

bool IsCrossingBackAboveEmas(int shift)
  {
   double closeNow = iClose(_Symbol, _Period, shift);
   double closePrev = iClose(_Symbol, _Period, shift + 1);
   double emaFastNow = EmaFast(shift);
   double emaSlowNow = EmaSlow(shift);
   double emaFastPrev = EmaFast(shift + 1);
   double emaSlowPrev = EmaSlow(shift + 1);

   bool wasAtOrBelow = closePrev <= emaFastPrev || closePrev <= emaSlowPrev;
   bool nowAbove = closeNow > emaFastNow && closeNow > emaSlowNow;
   return wasAtOrBelow && nowAbove && emaFastNow >= emaSlowNow;
  }

//+------------------------------------------------------------------+
//| Pattern detection                                                |
//+------------------------------------------------------------------+
bool GetBaseBreakSignal(double &stopLoss)
  {
   if(!InpTradeBaseBreak) return false;

   double baseHigh, baseLow;
   GetBaseRange(2, InpBaseLookback, baseHigh, baseLow);

   double close1 = iClose(_Symbol, _Period, 1);
   double close2 = iClose(_Symbol, _Period, 2);
   bool isBreakout = close1 > baseHigh && close2 <= baseHigh;

   if(IsTightBase(baseHigh, baseLow, 1) && IsAboveTrend(1) && isBreakout && IsStrongVolume(1))
     {
      double tickSize = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
      stopLoss = baseLow - (2 * tickSize);
      return true;
     }
   return false;
  }

bool GetWedgePopSignal(double &stopLoss)
  {
   if(!InpTradeWedgePop || InpWedgeLookback < 4) return false;

   double wedgeHigh, wedgeLow;
   GetBaseRange(2, InpWedgeLookback, wedgeHigh, wedgeLow);

   double earlyHigh = MathMax(iHigh(_Symbol, _Period, InpWedgeLookback + 1), iHigh(_Symbol, _Period, InpWedgeLookback));
   double lateHigh = MathMax(iHigh(_Symbol, _Period, 3), iHigh(_Symbol, _Period, 2));
   double earlyLow = MathMin(iLow(_Symbol, _Period, InpWedgeLookback + 1), iLow(_Symbol, _Period, InpWedgeLookback));
   double lateLow = MathMin(iLow(_Symbol, _Period, 3), iLow(_Symbol, _Period, 2));

   bool lowerHighs = lateHigh < earlyHigh;
   bool higherLows = lateLow > earlyLow;
   bool pop = iClose(_Symbol, _Period, 1) > wedgeHigh && iClose(_Symbol, _Period, 2) <= wedgeHigh;
   bool continuation = iClose(_Symbol, _Period, InpWedgeLookback + 1) > EmaSlow(InpWedgeLookback + 1);

   if(lowerHighs && higherLows && pop && continuation && IsAboveTrend(1) && IsStrongVolume(1))
     {
      double tickSize = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
      stopLoss = wedgeLow - (2 * tickSize);
      return true;
     }
   return false;
  }

bool GetEmaCrossbackSignal(double &stopLoss)
  {
   if(!InpTradeEmaCrossback) return false;
   if(!IsCrossingBackAboveEmas(1)) return false;
   if(!IsStrongVolume(1)) return false;

   double baseHigh, baseLow;
   GetBaseRange(2, MaxInt(3, InpBaseLookback / 2), baseHigh, baseLow);
   if(!IsTightBase(baseHigh, baseLow, 1)) return false;

   double tickSize = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
   stopLoss = MathMin(baseLow, iLow(_Symbol, _Period, 1)) - (2 * tickSize);
   return true;
  }

bool IsWedgeDropExit()
  {
   if(!InpExitWedgeDrop || InpWedgeLookback < 4) return false;

   double wedgeHigh, wedgeLow;
   GetBaseRange(2, InpWedgeLookback, wedgeHigh, wedgeLow);

   double earlyHigh = MathMax(iHigh(_Symbol, _Period, InpWedgeLookback + 1), iHigh(_Symbol, _Period, InpWedgeLookback));
   double lateHigh = MathMax(iHigh(_Symbol, _Period, 3), iHigh(_Symbol, _Period, 2));
   double earlyLow = MathMin(iLow(_Symbol, _Period, InpWedgeLookback + 1), iLow(_Symbol, _Period, InpWedgeLookback));
   double lateLow = MathMin(iLow(_Symbol, _Period, 3), iLow(_Symbol, _Period, 2));

   bool lowerHighs = lateHigh < earlyHigh;
   bool lowerLows = lateLow < earlyLow;
   bool supportBreak = iClose(_Symbol, _Period, 1) < wedgeLow && iClose(_Symbol, _Period, 2) >= wedgeLow;
   bool belowFastEma = iClose(_Symbol, _Period, 1) < EmaFast(1);

   return lowerHighs && lowerLows && supportBreak && belowFastEma;
  }

bool HasScaleInConfirmation()
  {
   int ownBuys = CountOwnPositions(POSITION_TYPE_BUY);
   if(ownBuys <= 0) return true;
   if(ownBuys >= InpMaxPositions) return false;

   double bid, ask;
   if(!GetTickPrices(bid, ask)) return false;

   double bestOpen = GetBestOpenPrice();
   if(bestOpen <= 0) return false;
   if(bid - bestOpen < PipsToPrice(InpMinScaleInProfitPips)) return false;

   return true;
  }

//+------------------------------------------------------------------+
//| Order execution                                                  |
//+------------------------------------------------------------------+
double NormalizeLotSize(double lotSize)
  {
   double stepVol = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);
   double minLot = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);
   double maxLot = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX);

   if(stepVol <= 0) stepVol = 0.01;
   lotSize = MathFloor(lotSize / stepVol) * stepVol;

   int volumeDigits = 0;
   double tmpStep = stepVol;
   while(tmpStep < 1.0 && volumeDigits < 8)
     {
      tmpStep *= 10.0;
      volumeDigits++;
     }
   lotSize = NormalizeDouble(lotSize, volumeDigits);

   if(lotSize > maxLot) lotSize = maxLot;
   if(lotSize < minLot) return 0;
   return lotSize;
  }

bool IsStopDistanceValid(double stopLoss)
  {
   double bid, ask;
   if(!GetTickPrices(bid, ask)) return false;

   int stopsLevel = (int)SymbolInfoInteger(_Symbol, SYMBOL_TRADE_STOPS_LEVEL);
   double minDistance = stopsLevel * _Point;
   if(minDistance <= 0) return true;
   return ask - stopLoss > minDistance;
  }

void OpenBuyTrade(double stopLoss, string signalName)
  {
   double bid, ask;
   if(!GetTickPrices(bid, ask)) return;
   if(!IsSpreadAllowed()) return;
   if(g_lastEntryBarTime == iTime(_Symbol, _Period, 0)) return;

   stopLoss = NormalizePrice(stopLoss);
   if(stopLoss >= ask || !IsStopDistanceValid(stopLoss)) return;

   double tickSize = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
   double tickValue = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
   if(tickSize <= 0 || tickValue <= 0) return;

   double ticks = (ask - stopLoss) / tickSize;
   if(ticks <= 0) return;

   int ownBuys = CountOwnPositions(POSITION_TYPE_BUY);
   double riskPercent = (ownBuys == 0) ? InpRiskPercent : InpScaleInRiskPercent;
   if(riskPercent <= 0) return;

   double riskAmount = AccountInfoDouble(ACCOUNT_BALANCE) * (riskPercent / 100.0);
   double lotSize = NormalizeLotSize(riskAmount / (ticks * tickValue));
   if(lotSize <= 0) return;

   string comment = InpTradeComment + " " + signalName;
   if(!g_trade.Buy(lotSize, _Symbol, ask, stopLoss, 0.0, comment))
     {
      Print("Buy ", signalName, " failed. Retcode=", g_trade.ResultRetcode(), " Error #", GetLastError());
      return;
     }

   g_lastEntryBarTime = iTime(_Symbol, _Period, 0);
  }

//+------------------------------------------------------------------+
//| Check Entry Logic                                                |
//+------------------------------------------------------------------+
void CheckEntry()
  {
   if(!HasEnoughBars()) return;
   if(CountOwnPositions(POSITION_TYPE_BUY) >= InpMaxPositions) return;
   if(!HasScaleInConfirmation()) return;

   double stopLoss = 0;

   if(GetBaseBreakSignal(stopLoss))
     {
      OpenBuyTrade(stopLoss, "BaseBreak");
      return;
     }

   if(GetWedgePopSignal(stopLoss))
     {
      OpenBuyTrade(stopLoss, "WedgePop");
      return;
     }

   if(GetEmaCrossbackSignal(stopLoss))
     {
      OpenBuyTrade(stopLoss, "EmaCrossback");
      return;
     }
  }

//+------------------------------------------------------------------+
//| Check Exit Logic                                                 |
//+------------------------------------------------------------------+
void CheckExit()
  {
   if(!HasEnoughBars()) return;

   double emaFast1 = EmaFast(1);
   double emaSlow1 = EmaSlow(1);
   double close1 = iClose(_Symbol, _Period, 1);
   double high1 = iHigh(_Symbol, _Period, 1);
   double open1 = iOpen(_Symbol, _Period, 1);
   double atr1 = Atr(1);

   bool emaCrossbackExit = close1 < emaFast1 && close1 < emaSlow1;
   bool exhaustionExtension = false;
   bool wedgeDropExit = IsWedgeDropExit();

   if(InpExitExhaustionExtension && atr1 > 0)
     {
      double extensionFromSlowEma = high1 - emaSlow1;
      bool extended = extensionFromSlowEma >= (InpExtensionAtrMultiple * atr1);
      bool rejection = close1 < open1 || close1 < iClose(_Symbol, _Period, 2);
      exhaustionExtension = extended && rejection;
     }

   if(!emaCrossbackExit && !exhaustionExtension && !wedgeDropExit) return;

   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0 || !PositionSelectByTicket(ticket)) continue;

      if(PositionGetString(POSITION_SYMBOL) != _Symbol) continue;
      if((int)PositionGetInteger(POSITION_MAGIC) != InpMagicNumber) continue;
      if((ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE) != POSITION_TYPE_BUY) continue;

      if(!g_trade.PositionClose(ticket))
         Print("PositionClose failed. Ticket=", ticket, " Retcode=", g_trade.ResultRetcode(), " Error #", GetLastError());
     }
  }

//+------------------------------------------------------------------+
//| Manage Trailing Stop                                             |
//+------------------------------------------------------------------+
void ManageTrailingStop()
  {
   if(InpTrailingStopPips <= 0) return;

   double bid, ask;
   if(!GetTickPrices(bid, ask)) return;

   double pipsToPrice = PipsToPrice(InpTrailingStopPips);
   double stopLevel = (int)SymbolInfoInteger(_Symbol, SYMBOL_TRADE_STOPS_LEVEL) * _Point;

   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0 || !PositionSelectByTicket(ticket)) continue;

      if(PositionGetString(POSITION_SYMBOL) != _Symbol) continue;
      if((int)PositionGetInteger(POSITION_MAGIC) != InpMagicNumber) continue;
      if((ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE) != POSITION_TYPE_BUY) continue;

      double openPrice = PositionGetDouble(POSITION_PRICE_OPEN);
      double currentSl = PositionGetDouble(POSITION_SL);
      double currentTp = PositionGetDouble(POSITION_TP);

      if(bid - openPrice > pipsToPrice)
        {
         double newSl = NormalizePrice(bid - pipsToPrice);
         if(stopLevel > 0 && bid - newSl <= stopLevel) continue;

         if(currentSl < newSl || currentSl == 0)
           {
            if(!g_trade.PositionModify(ticket, newSl, currentTp))
               Print("PositionModify trailing stop failed. Ticket=", ticket, " Retcode=", g_trade.ResultRetcode(), " Error #", GetLastError());
           }
        }
     }
  }

//+------------------------------------------------------------------+
//| Update Dashboard Info                                            |
//+------------------------------------------------------------------+
void UpdateDashboard()
  {
   if(!HasEnoughBars())
     {
      Comment("=== Oliver Kell Strategy (MT5) ===\n\nWaiting for enough bars...");
      return;
     }

   long avgVol = AverageVolume(2, InpVolMaPeriod);
   long lastVol = (long)iVolume(_Symbol, _Period, 1);
   double emaFast0 = EmaFast(0);
   double emaSlow0 = EmaSlow(0);

   double baseHigh, baseLow;
   GetBaseRange(2, InpBaseLookback, baseHigh, baseLow);
   bool baseTight = IsTightBase(baseHigh, baseLow, 1);

   double stopLoss = 0;
   bool baseBreak = GetBaseBreakSignal(stopLoss);
   bool wedgePop = GetWedgePopSignal(stopLoss);
   bool emaCrossback = GetEmaCrossbackSignal(stopLoss);

   double bid, ask;
   GetTickPrices(bid, ask);

   string dashboard = "=== Oliver Kell Strategy (MT5) ===\n\n";
   dashboard += StringFormat("Fast EMA (%d): %.5f\n", InpEmaFastPeriod, emaFast0);
   dashboard += StringFormat("Slow EMA (%d): %.5f\n", InpEmaSlowPeriod, emaSlow0);
   dashboard += "Last Vol: " + IntegerToString(lastVol) + " (Avg " + IntegerToString(InpVolMaPeriod) + ": " + IntegerToString(avgVol) + ")\n";
   dashboard += StringFormat("Spread: %.1f pips\n\n", (ask - bid) / PipsToPrice(1));

   dashboard += "=== Pattern Status ===\n";
   dashboard += StringFormat("Base High: %.5f | Base Low: %.5f\n", baseHigh, baseLow);
   dashboard += StringFormat("Base Tight: %s\n", baseTight ? "YES" : "NO");
   dashboard += StringFormat("Base Break: %s\n", baseBreak ? "YES" : "NO");
   dashboard += StringFormat("Wedge Pop: %s\n", wedgePop ? "YES" : "NO");
   dashboard += StringFormat("EMA Crossback: %s\n", emaCrossback ? "YES" : "NO");
   dashboard += StringFormat("Wedge Drop Exit: %s\n\n", IsWedgeDropExit() ? "YES" : "NO");

   dashboard += "=== Risk Management ===\n";
   dashboard += StringFormat("Initial Risk: %.2f%% | Scale-in Risk: %.2f%%\n", InpRiskPercent, InpScaleInRiskPercent);
   dashboard += StringFormat("Max Positions: %d | Open: %d\n\n", InpMaxPositions, CountOwnPositions(POSITION_TYPE_BUY));

   dashboard += "=== Current Status ===\n";
   bool hasPos = false;
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0 || !PositionSelectByTicket(ticket)) continue;

      if(PositionGetString(POSITION_SYMBOL) != _Symbol) continue;
      if((int)PositionGetInteger(POSITION_MAGIC) != InpMagicNumber) continue;

      string posTypeStr = ((ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE) == POSITION_TYPE_BUY) ? "BUY" : "SELL";
      dashboard += StringFormat("%s %.2f Lots @ %.5f\n", posTypeStr, PositionGetDouble(POSITION_VOLUME), PositionGetDouble(POSITION_PRICE_OPEN));
      dashboard += StringFormat("Stop Loss: %.5f | Profit: %.2f\n", PositionGetDouble(POSITION_SL), PositionGetDouble(POSITION_PROFIT));
      hasPos = true;
     }

   if(!hasPos)
      dashboard += "Waiting for Base 'n Break, Wedge Pop or EMA Crossback...\n";

   Comment(dashboard);
  }
//+------------------------------------------------------------------+
