<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <OutputPath>bin_v2\</OutputPath>
    <IntermediateOutputPath>obj_v2\</IntermediateOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="internal_run_migration.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql" />
  </ItemGroup>
</Project>
